### ISSUE TITLE
"People Using Kypsy" sort order

### ISSUE THREAD

**Issue by veganstraightedge** [kypsy/website#1]
> One more thing, I believe we discussed during the kick-off about the order of how other members would pop up when you browse through other members (i.e. currently the "People Using Kypsy” page). And they are supposed to pop up based on when they signed up (the newest people would be at the top of the feed). But, currently it’s set up so the same oldest members are always the first to pop up. Could we change that order please?

**Comment by mj90291** [comment]
Hi Shane, so I checked the result of this again today. And it seems that the issue may have been only partially resolved? You (first one to sign up) still show up as the first person when I click on the logo with multiple people (i.e. symbol for People using Kypsy page). But then my colleague who signed up most recently shows up after you. And starting from him and on, people seem to show up as intended (i.e. Newest sign-up first, oldest sign-up last.) Could we please reopen this issue until that's been sorted out?

**Comment by veganstraightedge** [comment]
I dug and dug into this and I think it was an illusion.

The users were:

["Brian Clarke", "Shane Becker", "Dennis Ta", "bookis", "Dbora Kim", "John Teague", "Maxine Jung", "Shane Becker"]

I had two accounts for testing: 1 from Twitter, 1 from Facebook.

I've deleted my FB one. That should resolve it for you.

**Comment by mj90291** [comment]
OK, the order seems as intended ATM. 

Additional questions for you:

- [ ] Does one same email used on multiple social websites have to create multiple accounts as seen on Kypsy? Shouldn't the account be able to be consolidated as long as it comes from one same email address in order to reduce confusion as seen in this issue? For example, I use maxinejung@gmail.com for Insta and FB. Sometimes I shop online with either one of the social media accounts as my sign-in credential for a shopping website even if I initially signed up on the shopping site with my email address. And they are able to pull the correct order history regardless whether I used my social media account or gmail account because the email is the same. **Can we allow users access the same account whether they signed up with Twitter or FB as long as the email info we collect is the same?**

- [ ]  Do you know who "bookis" is? I don't recognize that as any of my acquaintances. Could you please let me know their name and email address just in case I know that person please?

**Comment by veganstraightedge** [comment]
Bookis is my partner on Date Edge and helped me fix the photo uploader. So, he created an account in the process.

**Comment by veganstraightedge** [comment]
The short answer to the email question is no.

We don't know your email address from fb or tw until you're already signed up/in, at which point you've already got a Kypsy account. This is why I originally had the messaged saying to pair your other account too (fb or tw), so no matter which one a user signed in with it worked. Would you like me to re-add that message?

**Comment by mj90291** [comment]
- Re: 'bookis'. Ok, please make sure no one else signs up or sees Kypsy unless first consented by me as it is not open to public yet. 

- Re: account consolidation. So, the user has to pair them on their own in their settings? I don't remember doing that for other websites, and making the use do that manually sounds cumbersome... Let me process this first and get back to you.

**Comment by veganstraightedge** [comment]
Ok. When you decide, please create a new issue for that.

**Comment by mj90291** [comment]
Moved issue below to #22.
----------------------------------------------------------------------------
You mentioned above "We don't know your email address from fb or tw until you're already signed up/in, at which point you've already got a Kypsy account." But, that still doesn't sound to me that we could not automatically consolidate user accounts on the backend after they sign up/in. And it's kinda crazy that whenever someone signs in or signs up with FB or Twtitter account under the same email address, Kypsy would create multiple accounts for them resulting in unnecessary dupe accounts and confusion as already seen. Imagine that with 100 people let alone with thousands. 

- [ ] Is there anyway we can automate the account consolidation process for the user instead of them having to do it manually?
